<?php

namespace AppBundle\Repository;

/**
 * FinancialYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialYearRepository extends \Doctrine\ORM\EntityRepository
{
}
