<?php

namespace AppBundle\Repository;

/**
 * FunctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FunctionAssocRepository extends \Doctrine\ORM\EntityRepository
{
}
