<?php

namespace AppBundle\Repository;

/**
 * JobAttributRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobAttributRepository extends \Doctrine\ORM\EntityRepository
{
}
