index:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: home, permanent: true }

home:
    path: /{_locale}/
    defaults: { _controller: AppBundle:Default:home }

# Include AppBundle routes
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /{_locale}