security:
    providers:
        db_provider:
            entity:
                class: AppBundle\Entity\User
                property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: app_security_login
                check_path: app_security_login
                username_parameter: app_security_username
                password_parameter: app_security_password
            logout:
                path: app_security_logout
                invalidate_session: true

    access_control:
        - { path: ^/fr/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USER}