AppBundle\Entity\Employee:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EmployeeRepository
    manyToOne:
        organisation:
            targetEntity: AppBundle\Entity\Organisation
            inversedBy: employees
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: '50'
        lastname:
            type: string
            length: '50'
        createdAt:
            type: datetime
            column: created_ad
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
