AppBundle\Entity\Group:
    type: entity
    table: security_group
    repositoryClass: AppBundle\Repository\GroupRepository
    oneToMany:
        users:
            targetEntity: AppBundle\Entity\User
            mappedBy: group
            cascade: ["remove"]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 50
        roles:
            type: array
        createdAt:
            type: datetime
            column: created_ad
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    separator: '-'
                    fields:
                        - name
    lifecycleCallbacks: {  }
